Task to build core snap in launchpad
This job triggers the builds in launchpad for the different
architectures every night, and tracks the relation between the build and
the commit in git to be used to run tests.

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -3,5 +3,30 @@
 mkdir -p bin
 ( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )
 
-cp ./options target/tasks/snapd-vendor-sync
-cd target && ../bin/spread -v linode:
+export RESULTS_FILE=built_architectures.txt
+
+# build core for all the architectures
+output=0
+if ! python lp-build-core.py; then
+    echo "Failed to build snaps, results not updated"
+    output=1
+fi
+
+# check if results were generated
+if [ ! -f $RESULTS_FILE ]; then
+    echo "results file not created, exiting"
+    exit 1
+fi
+
+# check if results were generated
+if [ ! -f $RESULTS_FILE ]; then
+    echo "results file not created, exiting"
+    exit 1
+fi
+
+# run sync with build results
+cp ./options target/tasks/sync-build-commits
+mv $RESULTS_FILE target/tasks/sync-build-commits
+cd target && ../bin/spread -v -debug linode:
+
+exit $output
