Adding check to validate if the same core was uploaded to staging

diff --git a/target/tasks/core-sync/task.yaml b/target/tasks/core-sync/task.yaml
--- a/target/tasks/core-sync/task.yaml
+++ b/target/tasks/core-sync/task.yaml
@@ -18,6 +18,7 @@ prepare: |
 restore: |
     apt remove -y curl jq snapcraft
     rm -rf ${HOME}/.config/snapcraft
+    rm -f *.snap
 
 execute: |
     download_url=$(curl -s -H "X-Ubuntu-Architecture: $CORE_ARCH" -H 'X-Ubuntu-Series: 16' https://search.apps.ubuntu.com/api/v1/snaps/details/core?channel=${CORE_CHANNEL} | jq -j '.anon_download_url')
@@ -26,4 +27,18 @@ execute: |
     output=$(snapcraft push core.snap)
 
     revision=$(echo "$output" | sed -n "s|Revision \(.*\) of 'core' created\.|\1|p")
-    snapcraft release core $revision ${CORE_CHANNEL}
+    if snapcraft release core $revision ${CORE_CHANNEL}; then
+        echo "Core snap uploaded successfully"
+        exit 0
+    else
+        echo "In case the core could not be uploaded, check if the snaps are the same"
+        download_staging_url=$(curl -s -H "X-Ubuntu-Architecture: $CORE_ARCH" -H 'X-Ubuntu-Series: 16' $UBUNTU_STORE_SEARCH_ROOT_URL/api/v1/snaps/details/core?channel=${CORE_CHANNEL} | jq -j '.anon_download_url')
+        curl -L -o core_staging.snap "$download_staging_url"
+        if diff core.snap core_staging.snap; then
+            echo "Trying to upload same core image to staging"
+            exit 0
+        else
+            echo "Failed to upload different core image to staging"
+            exit 1
+        fi
+    fi
